# Generated by Django 2.2.3 on 2019-07-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order_item',
            unique_together=set(),
        ),
    ]
